name: CI-CD (ECR)

on:
  push:
    branches: [ main ]
  workflow_dispatch:

env:
  REPO_NAME: devops-interview-app

jobs:
  # -----------------------
  # CI Job
  # -----------------------
  ci:
    runs-on: ubuntu-latest
    outputs:
      image-tag: ${{ steps.set-tag.outputs.IMAGE_TAG }}
      ecr-registry: ${{ steps.login-ecr.outputs.registry }}
    steps:
      - uses: actions/checkout@v4

      - name: Set Image Tag
        id: set-tag
        run: echo "IMAGE_TAG=${GITHUB_SHA}" >> $GITHUB_OUTPUT

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Build and Push Image to ECR
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
        run: |
          docker build -t $ECR_REGISTRY/$REPO_NAME:${{ github.sha }} -f docker/Dockerfile .
          docker push $ECR_REGISTRY/$REPO_NAME:${{ github.sha }}

  # -----------------------
  # CD Job
  # -----------------------
  cd:
    name: CD - Deploy to EKS
    needs: ci
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Update kubeconfig
        run: |
          aws eks update-kubeconfig \
            --region ${{ secrets.AWS_REGION }} \
            --name devops-eks

      - name: Deploy with Helm
        run: |
          # --wait:  等待 pods 就緒，失敗就報錯（但不 rollback）
          # --atomic:    部署失敗時自動 rollback 到上一個成功版本
          # --timeout:   等待 pods 就緒的最長時間，超時視為失敗並觸發 rollback
          helm upgrade my-nginx ./helm/nginx-chart \
            --install \
            --wait \
            --namespace default \
            --set image.repository=${{ needs.ci.outputs.ecr-registry }}/$REPO_NAME \
            --set image.tag=${{ needs.ci.outputs.image-tag }}
